import * as fs from 'fs';
import * as path from 'path';
import { TestPlan, TestAction, GeneratedCode } from '../types';
import { validateSpec } from './spec-validator';

// Relative path from generated/ to the action library
const ACTIONS_IMPORT_PATH = '../src/actions';

function escapeQuotes(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Maps a single TestAction to Action Library call(s).
 * Raw Playwright APIs are only used for 'wait' (no library equivalent needed).
 */
function actionToCode(action: TestAction): string[] {
  const comment = `// ${action.description}`;
  switch (action.action) {
    case 'navigate':
      return [comment, `await navigateTo(page, '${escapeQuotes(action.value || '/')}');`];

    case 'fill':
      return [
        comment,
        `await fillInput(page, '${escapeQuotes(action.selector || '')}', '${escapeQuotes(action.value || '')}');`,
      ];

    case 'click':
      return [comment, `await clickElement(page, '${escapeQuotes(action.selector || '')}');`];

    case 'assert_visible':
      return [comment, `await assertVisible(page, '${escapeQuotes(action.selector || '')}');`];

    case 'assert_text':
      if (action.selector) {
        return [
          comment,
          `await assertText(page, '${escapeQuotes(action.value || '')}', '${escapeQuotes(action.selector)}');`,
        ];
      }
      return [comment, `await assertText(page, '${escapeQuotes(action.value || '')}');`];

    case 'assert_url':
      return [comment, `await assertUrl(page, '${escapeQuotes(action.value || '')}');`];

    case 'wait':
      return [comment, `await page.waitForTimeout(${Number(action.value) || 1000});`];

    default:
      return [`// WARNING: unknown action type: ${(action as TestAction).action}`];
  }
}

/**
 * Collects the action library symbols actually used by the plan actions.
 * Only imports what is needed — avoids unused import warnings.
 */
function collectUsedImports(actions: TestAction[]): string[] {
  const used = new Set<string>();
  for (const a of actions) {
    switch (a.action) {
      case 'navigate':      used.add('navigateTo');    break;
      case 'fill':          used.add('fillInput');     break;
      case 'click':         used.add('clickElement');  break;
      case 'assert_visible': used.add('assertVisible'); break;
      case 'assert_text':   used.add('assertText');    break;
      case 'assert_url':    used.add('assertUrl');     break;
    }
  }
  return [...used].sort();
}

/**
 * Generates a complete Playwright spec file from a TestPlan.
 * Generated code calls the Action Library instead of raw Playwright APIs —
 * fix a selector in the library and all tests using it are healed.
 *
 * @param vocabVersion - Version string from the vocabulary registry.
 *   Recorded in the spec's provenance header.
 */
export function generateSpecFile(
  plan: TestPlan,
  outputDir: string,
  vocabVersion = 'unknown',
  pageModelHash = 'unknown',
  plannerVersion = 'unknown',
): GeneratedCode {
  const usedImports = collectUsedImports(plan.actions);
  const lines: string[] = [];

  lines.push(`import { test } from '@playwright/test';`);
  if (usedImports.length > 0) {
    lines.push(`import { ${usedImports.join(', ')} } from '${ACTIONS_IMPORT_PATH}';`);
  }
  lines.push('');
  lines.push(`// AUTO-GENERATED by ai-driven-qa-platform — DO NOT EDIT`);
  lines.push(`// Scenario:       ${plan.scenarioName}`);
  lines.push(`// Generated:      ${new Date().toISOString()}`);
  lines.push(`// VocabVersion:   ${vocabVersion}`);
  lines.push(`// PageModelHash:  ${pageModelHash}`);
  lines.push(`// PlannerVersion: ${plannerVersion}`);
  lines.push('');

  const safeScenarioName = escapeQuotes(plan.scenarioName);
  lines.push(`test('${safeScenarioName}', async ({ page }) => {`);

  for (const action of plan.actions) {
    const codeLines = actionToCode(action);
    for (const line of codeLines) {
      lines.push(`  ${line}`);
    }
    lines.push('');
  }

  lines.push(`});`);
  lines.push('');

  const content = lines.join('\n');

  // Validate syntax before writing — fail fast with a clear Stage 4 error
  const validation = validateSpec(content);
  if (!validation.valid) {
    throw new Error(
      `[Stage 4] Generated spec has syntax errors — aborting before write.\n` +
      validation.errors.map(e => `  ${e}`).join('\n'),
    );
  }

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const slug = plan.scenarioName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const filename = `${slug}.spec.ts`;
  const specFilePath = path.resolve(outputDir, filename);

  fs.writeFileSync(specFilePath, content, 'utf-8');

  return { specFilePath, content };
}
