// ============================================================
// Stage 1 output: BDD Parser
// ============================================================

export interface BDDStep {
  keyword: 'Given' | 'When' | 'And' | 'But' | 'Then';
  text: string;
}

export interface ParsedScenario {
  feature: string;
  scenario: string;
  steps: BDDStep[];
}

// ============================================================
// Stage 2 input: Exploration script
// ============================================================

export interface ExplorationStep {
  /** Action to perform. 'capture' snapshots the current page DOM into a PageModel. */
  action: 'navigate' | 'fill' | 'click' | 'wait' | 'capture';
  /** CSS/Playwright selector — required for 'fill' and 'click'. */
  selector?: string;
  /** Text value for 'fill'; target URL for 'navigate' and 'capture'. */
  value?: string;
  /** Milliseconds to wait — required for 'wait'. */
  ms?: number;
}

// ============================================================
// Stage 2 output: App Explorer
// ============================================================

export interface PageElement {
  type: 'button' | 'input' | 'link' | 'heading' | 'label' | 'text';
  tag: string;
  text: string;
  id: string;
  name: string;
  inputType?: string;
  selector: string;
  href?: string;
}

export interface PageModel {
  url: string;
  title: string;
  elements: PageElement[];
  /** Fraction of elements (0-1) whose best selector uses data-testid/data-cy/data-test. */
  testidCoverage?: number;
  /** Selectors present in the first capture but absent in a second pass 500ms later — potentially unstable. */
  unstableSelectors?: string[];
}

// ============================================================
// Stage 3 output: LLM Planner
// ============================================================

export interface TestAction {
  action:
    | 'navigate'
    | 'fill'
    | 'click'
    | 'assert_visible'
    | 'assert_text'
    | 'assert_url'
    | 'wait';
  selector?: string;
  value?: string;
  description: string;
  /** How this action was produced: resolved from vocabulary or generated by LLM. */
  source?: 'vocabulary' | 'llm';
}

export interface TestPlan {
  scenarioName: string;
  url: string;
  actions: TestAction[];
}

// ============================================================
// Stage 4 output: Code Generator
// ============================================================

export interface GeneratedCode {
  specFilePath: string;
  content: string;
}

// ============================================================
// Failure analysis
// ============================================================

export type FailureCategory =
  | 'selector_drift'   // Locator timeout — element no longer found by its selector
  | 'timing'           // Navigation / network timeout
  | 'bad_generation'   // TypeScript / module / syntax error in generated spec
  | 'missing_data'     // 404, empty page, no seed data
  | 'product_defect';  // Assertion mismatch — expected vs actual diverged

export interface FailureRecord {
  test: string;
  file: string;
  category: FailureCategory;
  suggestion: string;
  errorSummary: string;
}

export interface FailureAnalysis {
  runAt: string;
  specFile: string;
  totalFailed: number;
  failures: FailureRecord[];
}

// ============================================================
// Stage 5 output: Runner
// ============================================================

export interface RunResult {
  passed: boolean;
  total: number;
  passedCount: number;
  failedCount: number;
  durationMs: number;
  specFilePath: string;
}
